//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAccesPdf.ModeloBd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDpdfSrcEntities1 : DbContext
    {
        public BDpdfSrcEntities1()
            : base("name=BDpdfSrcEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pdfsrc> pdfsrc { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    
        public virtual ObjectResult<sp_getUser_Result> sp_getUser(string pUser, string pPassword)
        {
            var pUserParameter = pUser != null ?
                new ObjectParameter("pUser", pUser) :
                new ObjectParameter("pUser", typeof(string));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getUser_Result>("sp_getUser", pUserParameter, pPasswordParameter);
        }
    }
}
