//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAccesPdf.ModeloBd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int idUsuario { get; set; }
        public string nUser { get; set; }
        public string nPassword { get; set; }
        public Nullable<int> Access { get; set; }
    }
}
